complete_from_path = true
path = ["/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/Library/Apple/usr/bin", "/nix/var/nix/profiles/default/bin", "/Users/evan/.nix-profile/bin"]
pivot_mode = "auto"
prompt = "STARSHIP_SHELL= starship prompt"
rm_always_trash = true
skip_welcome_message = true
startup = ["source ~/.config/nu/scripts/startup-commands.nu"]
table_mode = "rounded"

[env]
ALACRITTY_LOG = "/var/folders/9h/rfw2b99j02zcbv8g8knn_btr0000gn/T/Alacritty-22167.log"
CMD_DURATION_MS = "19"
COLORTERM = "truecolor"
COMMAND_MODE = "unix2003"
EDITOR = "nvim"
HOME = "/Users/evan"
LC_ALL = "en_US.UTF-8"
LESSHISTFILE = "/Users/evan/.config/less/history"
LOGNAME = "evan"
NIX_SSL_CERT_FILE = "/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt"
PYTHONSTARTUP = "/Users/evan/.config/python/startup.py"
SHELL = "/Users/evan/.local/share/nu/bin/nu"
SHLVL = "1"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.W07V0hpndc/Listeners"
STARSHIP_SESSION_KEY = "7192302502497132"
STARSHIP_SHELL = "nu"
TERM = "xterm-256color"
TMPDIR = "/var/folders/9h/rfw2b99j02zcbv8g8knn_btr0000gn/T/"
USER = "evan"
VISUAL = "nvim"
XDG_CACHE_HOME = "/Users/evan/.cache"
XDG_CONFIG_HOME = "/Users/evan/.config"
XDG_DATA_HOME = "/Users/evan/.local/share"
XDG_STATE_HOME = "/Users/evan/.local/state"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
__CFBundleIdentifier = "io.alacritty"
__CF_USER_TEXT_ENCODING = "0x1F5:0x0:0x0"

[line_editor]
edit_mode = "vim"

[text_view]
colored_output = true
header = true
line_numbers = true
pager = "less"
paging_mode = "quitifonescreen"
