path = ["/usr/local/bin", "/usr/bin", "/bin", "/usr/sbin", "/sbin", "/Applications/VMware Fusion.app/Contents/Public", "/Library/Apple/usr/bin", "/Users/evan/.nix-profile/bin", "/Users/evan/.local/share/flutter/bin", "/Users/evan/.local/share/gem/bin", "/Users/evan/.local/share/nu/bin/"]
prompt = "STARSHIP_SHELL= starship prompt"
startup = ["source ~/.config/nu/scripts/startup-commands.nu"]

[env]
ALACRITTY_LOG = "/var/folders/9h/rfw2b99j02zcbv8g8knn_btr0000gn/T/Alacritty-22167.log"
CMD_DURATION_MS = "19"
COLORTERM = "truecolor"
COMMAND_MODE = "unix2003"
HOME = "/Users/evan"
LC_ALL = "en_US.UTF-8"
LESSHISTFILE = "/Users/evan/.config/less/history"
LESSKEY = "/Users/evan/.config/less/keys"
LOGNAME = "evan"
MACCHINA_CONF = "/Users/evan/.config/macchina/macchina.toml"
NIX_PROFILES = "/nix/var/nix/profiles/default /Users/evan/.nix-profile"
NIX_SSL_CERT_FILE = "/Users/evan/.nix-profile/etc/ssl/certs/ca-bundle.crt"
NVM_DIR = "/Users/evan/.local/share/nvm"
OLDPWD = "/Users/evan"
PWD = "/Users/evan"
PYTHONSTARTUP = "/Users/evan/.config/python/startup.py"
SHELL = "/Users/evan/.local/share/nu/bin/nu"
SHLVL = "1"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.W07V0hpndc/Listeners"
STARSHIP_SESSION_KEY = "7192302502497132"
STARSHIP_SHELL = "nu"
TERM = "xterm-256color"
TMPDIR = "/var/folders/9h/rfw2b99j02zcbv8g8knn_btr0000gn/T/"
USER = "evan"
XDG_CACHE_HOME = "/Users/evan/.cache"
XDG_CONFIG_HOME = "/Users/evan/.config"
XDG_DATA_HOME = "/Users/evan/.local/share"
XDG_STATE_HOME = "/Users/evan/.local/state"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
__CFBundleIdentifier = "io.alacritty"
__CF_USER_TEXT_ENCODING = "0x1F5:0x0:0x0"
